build:
	docker-compose build

up:
	docker-compose up -d
	@echo "Сервисы запущены:"
	@echo "  FastAPI: http://localhost:8001"
	@echo "  Redis: localhost:6380"
	@echo "  RabbitMQ UI: http://localhost:15673"

down:
	docker-compose down
